### PR TITLE
Verbose is not disabled when capture is streamed #2

### PR DESCRIPTION
**Pull request by ledazul**
RaspiStillYUV.c had the same issue as RaspiStill.c (#450)
Same fix is applied to RaspiStillYUV.c, and braces are added back to RaspiStill.c for consistency.

### CODE REVIEW

**Comment by 6by9** [comment]
If you're feeling really keen, then the same is true in RaspiVid (https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiVid.c#L960 and https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiVid.c#L2707) and RaspiVidYUV (https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiVidYUV.c#L610 and https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiVidYUV.c#L1474) :-)

**Comment by ledazul** [comment]
Fixed RaspiVid.c and RaspiVidYUV.c

**Comment by 6by9** [comment]
Thanks.
Due to the conflict (you really need to rebase your branch) I've cherry-picked and squashed your commit, and pushed again as part of a PR I needed to raise - https://github.com/raspberrypi/userland/pull/453

**Comment by 6by9** [comment]
#453 has been merged which picked up the same changes as these, and resolved the conflict.

**Pull request closed without merging**
