### PR TITLE
Converted all the command ID's to enums, code tidy

### PR DESCRIPTION
**Pull request by JamesH65**
Changed the command defgines to enum
Removed any remaining tabs and replaced with spaces.

### CODE REVIEW

**Comment by JamesH65** [comment]
Damn, completely forgot about those. Will add them. There's some other defines elsewhere I may do as well, just to get them all out out of the way.

**Comment by JamesH65** [comment]
@6by9 One last review?

**Comment by 6by9** [comment]
Not looked too closely, but looks good.
Changing all that whitespace makes reviewing it awkward :-/

**Comment by 6by9** [comment]
Separate commit in the PR would have been fine. It might be worth doing a mega-blitz on whitespace over the whole of raspicam in one hit, and then at least future patches should be clean.

**Pull request merged**
