### PR TITLE
Remove vcos_get_free_mem()

### PR DESCRIPTION
**Pull request by luked99**
This function isn't used anywhere, and causes compiler warnings
due to its use of sbrk() without the relevant #defines.

The "pthreads" version of this doesn't do anything sensible: on
a linux system it should look at something like /proc/vmstat,
but that's not what it does. So additionally remove it to avoid
confusion.

See issue #316.

### CODE REVIEW

**Comment by 6by9** [comment]
Checking full firmware source, it is used directly in RUT, audio tests, ARTS performance, and ILTest.
Admittedly those haven't been used in a fair while (self hosted was broken last time I tried), but it's probably safer to drop the pthreads version to being "return 0;" rather than removing the whole function and prototype.

**Comment by popcornmix** [comment]
Agreed - we don't currently build any of the test apps that call vcos_get_free_mem, but they are in the tree and could be built in theory.
Considering it deprecated and allowing "return 0" seems a reasonable option.
(if removing it a few other prototypes would need removing anyway).

**Comment by luked99** [comment]
Better still, make it with __attribute__((deprecated)) ?

**Comment by popcornmix** [comment]
Do we have a portable way of doing that? Would need to compile with hcvc, msvc, gcc etc.

**Comment by luked99** [comment]
Perhaps something like:


    #ifdef __GNUC__
    #define VCOS_DEPRECATED __attribute__((deprecated))
    #else
    #define VCOS_DEPRECATED
    #endif

Then put VCOS_DEPRECATED in the pthreads header file but not the common one (which may or may not be accepted by the compiler).

Totally untested.

**Comment by luked99** [comment]
877efd2a55516e76247b54a23d9a996092fe54a0 deprecates the pthreads version of vcos_get_free_mem().

**Comment by popcornmix** [comment]
Thanks.

**Pull request merged**
