### PR TITLE
Replace 'arch' with uname

### PR DESCRIPTION
**Pull request by solskogen**

### CODE REVIEW

**Comment by JamesH65** [comment]
Since `man arch` says "arch - print machine hardware name (same as uname -m)" this LGTM.

**Comment by popcornmix** [comment]
@solskogen can you explain why?
Are you running this on a distribution that doesn't support ``arch``?

**Comment by solskogen** [comment]
Not every distribution comes with "arch", which is used in buildme.

**Comment by popcornmix** [comment]
Which distribution are you using that doesn't have arch?

**Comment by solskogen** [comment]
Arch Linux ARM and Manjaro (which is based on Arch) doesn't come with 'arch', but when replaced with $(uname -m) it works perfectly.

**Comment by pelwell** [comment]
See https://github.com/raspberrypi/userland/issues/590 for context.

**Comment by pelwell** [comment]
LGTM.

**Pull request merged**
