### PR TITLE
Fix strict-aliasing

### PR DESCRIPTION
**Pull request by atupone**

### CODE REVIEW

**Comment by popcornmix** [comment]
Looks correct but is a bit ugly. I think doing the memcpy on a separate line might help a bit.
@pelwell @6by9 any thoughts?

**Comment by pelwell** [comment]
I think it's a shame, at least for the vchiq case, since header->data is guaranteed to be 4-byte aligned. But putting that aside, perhaps a function to read an integer from a char pointer might be a cleaner way of fixing this without having to change the indentation.

**Comment by atupone** [comment]
It's ugly :( , but it is really optimized, if you the compiled code

**Comment by 6by9** [comment]
Nothing to add, though very ugly.

I'm assuming the vcilcs_out.c include is just for a missing prototype rather than aliasing?

**Comment by atupone** [comment]
yes the include is for that

**Comment by atupone** [comment]
Maybe something like this

uint32_t makeCurrentId = EGLINTMAKECURRENT_ID;
if (thread->merge_pos == CLIENT_MAKE_CURRENT_SIZE && !memcmp(thread->merge_buffer,    
                                                                                                                   &makeCurrentId,
                                                                                                                    sizeof(makeCurrentId)))
is more acceptable ?

**Pull request merged**
