### PR TITLE
Added annotate and intrarefresh settings

### PR DESCRIPTION
**Pull request by JamesH65**
Added intra refresh type to raspivid(s)
Added an annotate parameters to allows insertion of various status' to stills or videos.

### CODE REVIEW

**Comment by JamesH65** [comment]
I've updated the PR with the corrections suggested by 6x9.  Any other comments before merging?

(and sorry it's really two change in one - not enough time to unpick and move them around)

**Comment by JamesH65** [comment]
Any objections? Will be merging by 7pm unless otherwise informed of impending disaster.

**Comment by popcornmix** [comment]
No objection. I compile tested it...

**Comment by JamesH65** [comment]
Good enough for me! We've been using it here, and seems OK.

**Pull request merged**
