### PR TITLE
Added command line parameters for overriding frame# in filename

### PR DESCRIPTION
**Pull request by rmamba**
-dt is for datetime
-ts is for timestamp
-hms is for HourMinuteSeconds

It overwrites the frame value in file name generated in timelaps mode

### CODE REVIEW

**Comment by JamesH65** [comment]
Apologies for the delay. This PR can no longer be merged due to other changes, and also, could you squash all the commits in to one to make it easier to see the changes in one go?

**Comment by rmamba** [comment]
@JamesH65 can I take 10 months to reply too? :)

**Comment by rmamba** [comment]
I merged upstream changes into mine. I'll recompile and test the code on rPi over the weekend

**Comment by popcornmix** [comment]
@rmamba You'll need to rebase (to remove the "Merge" commits) before we can pull this in.

**Comment by rmamba** [comment]
I rebased, but don't know if I did it correctly since it's the first time I had to do it.
I tested it on my rPi and it compiles and runs so should be OK.

raspistill -o img%d.jpg -ts  << TimeStamp
raspistill -o img%d.jpg -dt   << DateTime

**Comment by rmamba** [comment]
@popcornmix ready to merge if I did it correctly

**Comment by popcornmix** [comment]
No it still needs rebasing/squashing. This is showing as 18 commits. It should be 1.
Assuming raspberrypi/userland is set as a remote called upstream, run something like:
``
git pull --rebase upstream master
git rebase -i HEAD~18
# find the first commit of yours and change pick to squash for all subsequent ones
git push -f
```

**Comment by rmamba** [comment]
re-forked the project and applied changes. 
I had a binary edit of odt file and this is easier

will open new PR

**Pull request closed without merging**
