### PR TITLE
Added support for network and fflush to decrease latency.

### PR DESCRIPTION
**Pull request by Kixunil**
These changes allow users to stream video directly over network with lower latency (bypassing pipes and buffers). If file name has format tcp://host:port then TCP connection to host:port is opened. Similarly if udp:// is used, UDP packets with data are sent to host:port.

### CODE REVIEW

**Comment by JamesH65** [comment]
Would it be possible to use the same bracketing style as the rest of the code please (Allman).

**Comment by popcornmix** [comment]
Regularly calling fflush will reduce performance for the usual case (writing to sdcard) where we don't care about latency.

**Comment by JamesH65** [comment]
I'd suggest it would be worth putting the fflush as an optional parameter
just for those who need it..

**Comment by Kixunil** [comment]
Sorry to come back so late, I forgot about this PR. I fixed the braces and made optional switch to enable flushing. In case of other issues feel free to write me.

**Comment by Kixunil** [comment]
Sorry, I used tabs in vim. Fixed it.

**Comment by popcornmix** [comment]
Can you squash all commit to a single one and force push.
@JamesH65 @6by9 okay by you?

**Comment by Kixunil** [comment]
@popcornmix Done, is it OK?

**Comment by Kixunil** [comment]
Yeah, I prefer tabs and I'm very accustomed to using them. Sorry.

**Comment by JamesH65** [comment]
Using "f" as the short command line parameter conflicts with the preview -f
option - I'd suggest changing to -fl which I think is free. You need to
cross check with RaspiPreview.c, Raspistill/vid.c and RaspiCamControl.c to
find a 'spare' option.

**Comment by 6by9** [comment]
Content looks fine to me other than James having picked up on the clash of -f in the option.

**Comment by Kixunil** [comment]
@JamesH65 I didn't know that options should be conflict-free across different tools. I just changed it to -fl, as you suggested.

**Comment by JamesH65** [comment]
They are not different tools, as things like RaspiPreview are used across
multiple tools. Hence the requirement to keep things unique.

**Comment by Kixunil** [comment]
@JamesH65 OK, thanks for explanation!

**Pull request merged**
