### PR TITLE
Possible mistype in mmal_metadata.h

### PR DESCRIPTION
**Pull request by zeme-wana**
Possible mistype MMAL_META(T)DATA ...

### CODE REVIEW

**Comment by popcornmix** [comment]
@6by9 These are never used in the code so I guess it doesn't really matter.
What do you think? Rename/leave/delete?

**Comment by pelwell** [comment]
Rename or delete.

**Comment by 6by9** [comment]
Agreed - delete.

It was intended as an equivalent to the VC_IMAGE metadata structures. Seeing as there doesn't even appear to be an implementation of the function (only a prototype), get rid of it. There is a reference to it in mmal.h and CMakelists.txt (so it gets installed), so those out to be cleaned up too.

**Comment by popcornmix** [comment]
@6by9 do you mean delete the mmal_metadata.h file and the current include of it from mmal.h?

**Comment by 6by9** [comment]
Yes, delete mmal_metadata.h and the references to it in mmal.h and CMakelists.txt

**Pull request closed without merging**
