### PR TITLE
Some build fixes

### PR DESCRIPTION
**Pull request by ggardet**
Build fixes.

### CODE REVIEW

**Comment by popcornmix** [comment]
How are you building?
The first change is obviously fine.
The other's don't seem to be a problem for most users - I wonder what's different in your setup?

**Comment by ggardet** [comment]
Building with openSUSE native GCC toolchains (openSUSE 13.1, 13.2 and Tumbleweed (rolling release)).

**Comment by ggardet** [comment]
Ping

**Comment by popcornmix** [comment]
I think these changes are all in master of userland. Can you check it's okay for you?

**Comment by ggardet** [comment]
Yes, all changes are now included. 
Why did you recreate all commits instead of accepting my merge request?

**Comment by popcornmix** [comment]
The userland repo is actually generated from the internal GPU code repo.
In testing this PR, I merged it into the GPU repo first to see if any issues arose.
After building a firmware build, the diffs appeared in the userland repo and I forgot where they came from and so just pushed the diffs.
Sorry about not using merge PR directly - that was just an oversight.

**Comment by ggardet** [comment]
Ok. So, I will close this PR.

**Pull request closed without merging**
