### PR TITLE
Update the GPS version to 23

### PR DESCRIPTION
**Pull request by JamesH65**
Buster now has gpsd version 23, (up from 22)

This PR updates the camera code to reflect the change.

### CODE REVIEW

**Comment by JamesH65** [comment]
Note, the change to gps.h is simply a copy of the v23 version over the top of the v22 version.

**Comment by 6by9** [comment]
Do we want to just do this simplistic bump the version? It'll now be broken on Stretch.

I haven't looked at what symlinks or automagic mangling of the library name happens in dlopen, but it'd be nice to be able to load a generic library filename and then check against supported versions. Don't know if that is actually possible though.

**Comment by JamesH65** [comment]
> Do we want to just do this simplistic bump the version? It'll now be broken on Stretch.
> 
> I haven't looked at what symlinks or automagic mangling of the library name happens in dlopen, but it'd be nice to be able to load a generic library filename and then check against supported versions. Don't know if that is actually possible though.

I did wonder about that, but on the whole we only have support for the current version of the distro, ie backward rather than forward compatibility. Might be worth asking @XECDesign though.

**Comment by XECDesign** [comment]
Stretch is unlikely to get libraspberrypi0 updates. If you would like to provide an option for people to build it themselves, you could use ifdefs or dynamically load the appropriate .so at runtime and deal with whatever API differences might be relevant.

Personally, I'm in the "we don't support old releases" camp.

**Comment by 6by9** [comment]
Fine, ditch libgps.22

**Pull request merged**
