### PR TITLE
wayland support

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by popcornmix** [comment]
@6by9 any comments on the vcos inline changes (or cmake or others)?

**Comment by 6by9** [comment]
Sorry, lots of comments there, but I'm done now. 
If I haven't commented on a patch then either I'm happy or have no idea (mainly over EGL things)

**Comment by popcornmix** [comment]
I've cherry picked a few of the obvious fixed. 
@kraj it might be worth rebasing this PR and we'll see what is left.

**Comment by jgueytat** [comment]
Hi,

we are currently using this series of patches in meta-raspberrypi in Yocto.
I would like at least the patches related to pkg-config beeing integrated. There is by the way an issue related to those pkg-config files.
I'm also pretty sure that the other patches deserves attention.

Best Regards,

**Comment by popcornmix** [comment]
@XECDesign what do you think about "cmake: generate and install pkgconfig files"?

**Comment by XECDesign** [comment]
Assuming the pkgconfig files will be installed in /opt/vc/..., looks okay. As long as paths don't clash with the mesa libraries.

**Comment by jgueytat** [comment]
The *.pc files are generated and depends only on the prefix you give to CMake in the *.in files.

**Comment by Ruffio** [comment]
@popcornmix @XECDesign can this be merged?

**Comment by JamesH65** [comment]
@popcornmix  @XECDesign Given we no longer develop Wayland, can this PR be closed? It's 2 years since it was last commented on, so happy to close it, so....

This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by kraj** [comment]
I have kept this pull alive and I am still interested in merging this. We have it working with Openembedded/yocto for that time. So I would be interested in addressing any feedback if any

**Comment by raidensnake** [comment]
I know this may be old but it might prove useful for the RPi4 as an Alternative to X.

**Pull request closed without merging**
