### PR TITLE
RaspiStill: Read sensor information correctly if one of each type is …

### PR DESCRIPTION
**Pull request by 6by9**
…attached.

On a CM with one OV5647 and one IMX219, the setup of whichever sensor
is camera 0 was taken for both sensors. That meant the default resolution
and EXIF headers were wrong for the second camera.

### CODE REVIEW

**Comment by 6by9** [comment]
Ping @JamesH65 for review.

**Comment by JamesH65** [comment]
Looks fine to me.

**Comment by 6by9** [comment]
@popcornmix Do you want to review, or shall I merge?

**Comment by popcornmix** [comment]
Looks fine. Feel free to merge.

**Pull request merged**
