### PR TITLE
Wayland

### PR DESCRIPTION
**Pull request by tomeuv**
While waiting, I have fixed a couple of bugs regarding resource deallocation, making it more correct and perhaps more robust. Support has been already merged into Weston and people are waiting for this to be available in Raspbian to test. Thanks!

### CODE REVIEW

**Comment by evgenyz** [comment]
Is this initiative got abandoned (or I'm missing it's reincarnation somewhere)?

**Comment by ReubenM** [comment]
There are proper kernel and mesa drivers being developed that will render
this hack obsolete.

http://dri.freedesktop.org/wiki/VC4/

**Comment by fooishbar** [comment]
Right. The decision was to not work further on the old drivers, and wait for the new drivers (Mesa + KMS) to be developed. This is underway, as it has been for some time, and when they are complete, we should have native Wayland support. There is no currently-published ETA for this happening however.

**Comment by agherzan** [comment]
Hi @tomeuv there is a problem I encounter after I apply https://github.com/tomeuv/userland/commit/c22c00f1e430b105a2c3dbbeffcf4762f27c3b17 .

The
```
add_library(EGL ${SHARED} ${EGL_SOURCE})
```
in git/interface/khronos/CMakeLists.txt gets to run before the header is
generated. No dependency configured for that. And in the sources of EGL there
is egl_wayland.c which includes the generated header by the call:
````
wayland_add_protocol_server(
       EGL_SOURCE
       ../../interface/wayland/dispmanx.xml
       dispmanx
)
```
This leads me to the same error @ajlennon had pointed above.

Any hints on how to fix this?

**Comment by agherzan** [comment]
Ping?

**Comment by rzr** [comment]
This PR needs to be refreshed isnt it ?

For the record I noticed couple of work in process : 

https://github.com/agherzan/meta-raspberrypi/pull/1

https://github.com/agherzan/meta-raspberrypi/commit/2a84a6a9ba86cfc7c5a09f044651a636f96026c6

Seems this be backported to dizzy , is there someone maintaining a such branch ?

**Comment by fooishbar** [comment]
@rzr We have no plans to update this branch. The open-source Mesa 'vc4' driver for Raspberry Pi is a much better option to use, though you do need quite a new kernel. The driver this patches still has a number of issues when running under Wayland, which are not easily fixable.

**Comment by ppaalanen** [comment]
If you use Weston's rpi-backend, please see this and spread the word:
https://lists.freedesktop.org/archives/wayland-devel/2016-May/028764.html

**Comment by rzr** [comment]
Yea DRM support will be far better

**Comment by fooishbar** [comment]
@rzr Right, and that is very much our long-term plan. However, while KMS support is not enabled by default, we want to get an idea of how many people this would affect.

**Comment by Ruffio** [comment]
@tomeuv is this PR still relevant? If it is, the conflicts should be resolved...

**Comment by fooishbar** [comment]
@Ruffio No, the vc4 Mesa/KMS drivers resolve this for us.

**Comment by Ruffio** [comment]
Then please close the PR

**Comment by Ruffio** [comment]
@fooishbar as this has been resolved, please close/reject this PR...

**Comment by fooishbar** [comment]
@Ruffio I don't have permission to do so.

**Comment by Ruffio** [comment]
@popcornmix can you close/reject this PR?

**Comment by JamesH65** [comment]
Closing due to lack of activity. Please request to be reopened if you feel this issue is still relevant.

**Pull request closed without merging**
