### PR TITLE
raspicam: Improved readme with readme syntax

### PR DESCRIPTION
**Pull request by sjfricke**
Makes viewing much easier to read and  follow along

### CODE REVIEW

**Comment by JamesH65** [comment]
Looks OK to me.  That whole thing needs a bloody good once over (2013 being the date on it!). I'll try and find time at some point, must be a few missing commands.

**Comment by 6by9** [comment]
Merged. Thanks for your contribution.

**Comment by lurch** [comment]
Wasn't the decision made to keep the camera-apps documentation updated in the documentation repo?
https://github.com/raspberrypi/documentation/blob/master/raspbian/applications/camera.md

\*shrug\*

**Comment by 6by9** [comment]
@lurch You may be right that that was the intention - I can't remember. In which case the docs here need to get nuked and replaced with a link to there. I'll follow up.

**Pull request merged**
