### PR TITLE
CamApps : Removed version number and replace with commit id

### PR DESCRIPTION
**Pull request by JamesH65**
Changed CMakeLists.txt for the camera apps to grab the head commit
hash and pass it to the compiler as a define. Use this to version
the apps rather than the never updated version number.

### CODE REVIEW

**Comment by JamesH65** [comment]
This will presumably need the build for the apps to be done from the userland repo to make the hash most useful - not sure this is how it is done at the moment though.

**Comment by pelwell** [comment]
Ah ha - we have a CMake expert in our midst!

This looks plausible. Assuming it actually works (i.e. the commit ID extraction and quoting for the printf()s) then I approve.

**Comment by 6by9** [comment]
Check with @XECDesign as to how Raspbian will build this and does it get the right hash.

Does it actually behave if you download a snapshot tar/zip of the repo and build that? I've had a number of issues raised recently where I've asked what hash they're using to find they've downloaded a random snapshot.

**Comment by XECDesign** [comment]
Currently, everything is pulled in from the `firmware` when appropriate.

**Comment by 6by9** [comment]
> Currently, everything is pulled in from the firmware when appropriate.

Hmm, that could be entertaining as I suspect it'll get the hash of the firmware repo, not the hash of the userland repo which is what we really want.

**Comment by XECDesign** [comment]
Since the firmware repo just has pre-built binaries, it shouldn't.

**Comment by 6by9** [comment]
> Since the firmware repo just has pre-built binaries, it shouldn't.

My bad - I was thinking of hello_pi which is copied as source.
As long as we don't try applying this code to that then we're probably OK.

**Comment by XECDesign** [comment]
At some point we should move the libs and binaries out of /opt and provide proper packages (the way we're doing it right now is awful from a Debian packaging point of view). It may cause some issues when that happens, but nothing that we won't be able to work around.

**Comment by JamesH65** [comment]
@XECDesign Worth creating a new issue for that, if there isn't one already. Sounds like a sensible idea that should be implemented sooner rather than later. I cannot see the issues being too onerous.

**Comment by JamesH65** [comment]
Everyone happy to merge? I have tested all the apps, and definitely get the right commit ID .

**Comment by pelwell** [comment]
@6by9's concern about a non-git download needs addressing.

**Comment by JamesH65** [comment]
OK, will test that, although that was why I put in the #ifndef GIT_COMMIT_ID clause.

**Comment by JamesH65** [comment]
Although thinking about it, that won't work, I suspect you would get something like "Not a git repo" in the define rather than the commit ID. Will try it out.

**Comment by pelwell** [comment]
I was hoping that GitHub might add a (for example) .version file containing the head commit ID, but I can't find anything like that.

**Comment by JamesH65** [comment]
A non-git downloaded build gives this...

`raspistill Camera App (commit )`

So, builds OK, just nothing in the ID.

**Comment by popcornmix** [comment]
I've just tested with a firmware build and ``/opt/vc/bin/raspicam`` reports:
``raspivid Camera App (commit e5896a07ad5a)``
which is a commit hash from the internal vc4 repo rather than the userland repo.

**Comment by JamesH65** [comment]
Ah, bummer.

**Comment by pelwell** [comment]
Either we switch to building the utilities from userland or we live with the discrepancy - the information is still useful, just marginally harder to interpret.

**Comment by 6by9** [comment]
Insert the build date in the string? At least that is useful to the general user as much as us.

**Comment by popcornmix** [comment]
You might also want to consider added a ``(clean)``/``(tainted)`` flag (see ``interface/vcos/vcos_genversion``) as we do when building firmware.
It uses ``git status --porcelain`` to check if there are local edits to the tree it's been build from.

**Comment by JamesH65** [comment]
Might use something like `git ls-files -m | wc -l` which returns 0-n where n is the number of modified files.

**Comment by JamesH65** [comment]
OK, have also added the tainted flag as suggested by Dom.

However, because of changes I am making in the camera apps that conflict with this stuff, going to close this without merging, and  make another PR once the other stuff is done. Would appreciate any comments on this in the meantime.

**Comment by popcornmix** [comment]
No need for another PR. Once the other changes have been merged, just rebase this tree and force push and all will be good.

**Comment by JamesH65** [comment]
Rebased, debugged, and I think ready to go.

**Comment by pelwell** [comment]
Looks good to me.

**Comment by 6by9** [comment]
One thought - this is in the cmake rules, so does it get triggered if you just "make" from the right directory? I don't know where this gets inserted into the process.

**Comment by 6by9** [comment]
To answer my own question, it is only triggered when you call cmake, not on make.
I've built tainted code which doesn't declare itself as such, and vice versa.

**Comment by JamesH65** [comment]
I always do my build using the buildme script, which uses cmake, so nowt sure what other things might do.

**Comment by pelwell** [comment]
Ditto. Do we support any other method?

**Comment by 6by9** [comment]
I was only thinking that we have the relevant Makefile stuff in vc4 (interface/vcos/vcos_genversion), so was there benefit of not requiring the cmake step every time.
Parts of userland (eg hello_pi) can be built via make alone. For the rest you need to cmake once, but the rest of the time you can just make.
I'm not overly fussed either way, but thought I'd raise it.

**Pull request merged**
