### PR TITLE
Add AWB Grey World mode option.

### PR DESCRIPTION
**Pull request by naushir**
This mode should be used for NoIR cameras.
Only valid for the new RPi AWB algorithm.

### CODE REVIEW

**Comment by naushir** [comment]
@6by9 please have a look at this PR.

**Comment by JamesH65** [comment]
LGTM

**Comment by 6by9** [comment]
Looks fine.

**Comment by changmin711** [comment]
Hi Naushir,

I have same issue camera all purple pink picture.
I cannot find all the paths to the *.c *.h files no matter how many times i do a search for files or folder names.
I just installed the "Raspbian Buster with desktop and recommended software v4.19"  onto the MicroSD card and run it in RaspberryPi 2B. 
Kindly assist me how to find those files as i am new to this.

**Comment by naushir** [comment]
Please make sure your distribution is up-to-date by following the instructions at:
https://www.raspberrypi.org/documentation/raspbian/updating.md

Then follow the instructions to set awb grey wold in raspistill:
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=245994&sid=d1b6a4cc565def50e9168fa86effd74f

**Comment by changmin711** [comment]
Hi Naushir

Updated everything, updated with a fresh SD card on startup also, and i still cannot find the .c .h files to edit.
Is there any shortcut to find the files?  I cant even know where "host_applications" & "interface" folders is to start with, where to find it?  
Why is it so complicated just to do a simple file finding?
Pls help.
Its frustrating.

**Comment by 6by9** [comment]
```
git clone https://github.com/raspberrypi/userland
cd userland
./buildme
```

**Comment by changmin711** [comment]
> https://github.com/raspberrypi/userland

hi
Meaning?

**Comment by changmin711** [comment]
> This mode should be used for NoIR cameras.
> Only valid for the new RPi AWB algorithm.



> ```
> git clone https://github.com/raspberrypi/userland
> cd userland
> ./buil

> ```
> git clone https://github.com/raspberrypi/userland
> cd userland
> ./buildme
> ```

does changing to Pi3 or Pi4 settle this issue with the purple camera images?

**Pull request merged**
