### PR TITLE
Fixes for #34 and #142

### PR DESCRIPTION
**Pull request by 6by9**

### CODE REVIEW

**Comment by 6by9** [comment]
@JamesH65 and @msperl please review and test the filename sanity checking change.

**Comment by 6by9** [comment]
@msperl - patch updated to accept %<numerics>d, as well as %%, or %d.
Tested with and allows:
file%%%%
file%%%%.jpg
file%%%08d
file%%%%08d (valid, but doesn't use the frame number argument, just gives "file%%08d")

Rejects:
file%%%08x
file%s

(Probably shouldn't have forced updated this branch, but saves a squash later)

**Comment by msperl** [comment]
I guess "%.8d" is also valid in principle, but I guess nobody would use that - and if someone does then the workaround is to use "%08d".

At least it does not segfault any longer...

**Comment by popcornmix** [comment]
Thanks.

**Pull request merged**
