### PR TITLE
RaspiStill: Apply gpsd info as EXIF tags

### PR DESCRIPTION
**Pull request by jasaw**
Applies GPS information from gpsd as EXIF tags.
Enable via "-gps" command line argument and requires libgps.so.22 when
enabled.
Only these GPS info are added as EXIF tags: GPSDateStamp, GPSTimeStamp,
GPSMeasureMode, GPSSatellites, GPSLatitude, GPSLatitudeRef,
GPSLongitude, GPSLongitudeRef, GPSAltitude, GPSAltitudeRef, GPSSpeed,
GPSSpeedRef, GPSTrack, GPSTrackRef.

### CODE REVIEW

**Comment by jasaw** [comment]
Here's the binary I've prepared earlier.
[raspistill.gps.tar.gz](https://github.com/raspberrypi/userland/files/113257/raspistill.gps.tar.gz)

**Comment by jasaw** [comment]
Good catch on both the errors. I've pushed a fix for both of them.

**Comment by jasaw** [comment]
Here's a binary I've prepared earlier:
[raspistill.gps.tar.gz](https://github.com/raspberrypi/userland/files/115013/raspistill.gps.tar.gz)

**Comment by 6by9** [comment]
Sorry, I hadn't seen the email saying this had been updated.
That looks OK on a moderately quick glance. 

@popcornmix - are you happy with the licence header on the 2 new files? Looks OK to me as they are the same as those on the main RaspiStill files, but there's the subtle difference of Broadcom/James' code vs 3rd party. 

I suspect @popcornmix will ask you to squash the commits if he and @JamesH65 are happy with the changes.

**Comment by Ruffio** [comment]
@popcornmix are you happy with this PR?

**Comment by JamesH65** [comment]
@6by9 @jasaw this appears to have fallen through the cracks. Any thoughts on how to proceed?

**Comment by 6by9** [comment]
Still the open question to @popcornmix on licence of the two new files, other than that (and needing to rebase and resolve conflicts) I'm happy.

**Comment by JamesH65** [comment]
@jasaw Sorry about the delay, can you rebase this please to remove conflicts, then we can try and get it merged.

@popcornmix Any objections?

**Comment by popcornmix** [comment]
The new files appear to have the same 3 clause BSD licence we use for our code (with a different copyright author). That should be fine for us.

No objections here if you are happy.

**Comment by moose4621** [comment]
How do I call the gps data in raspistill. ie: -x GPS.GPSLatitude = ?

I would like to use this feature of raspistill. Any chance it can be merged anytime soon?

**Comment by jasaw** [comment]
@moose4621 This PR reads GPS data from gpsd and records them as GPS EXIF tags. The purpose is to have GPS EXIF tags automatically update when raspistill is running in continuous mode. There's no need to specify GPSLatitude etc from command line.

**Comment by moose4621** [comment]
Great. Thank you.@jasaw.
Works a treat!
Awesome work.
Need to get this great function merged.

**Comment by moose4621** [comment]
@jasaw  is there any way to make this feature available when taking single images instead of continuous mode?

**Comment by 6by9** [comment]
@JamesH65 you had said you had a GPS receiver at home and were going to bring it in to test.

I'll try to find 5 minutes to give it a whirl. As long as it doesn't mess up existing installs where there is no GPS device, then I'm happy.

**Comment by kukabu** [comment]
@6by9 You can uses gpsfake for tests.
http://catb.org/gpsd/gpsfake.html

**Comment by 6by9** [comment]
Tested with gpsfake and I'm happy.
Bombing out should -gps be set but gpsd/gpsfake not running may be a tad extreme, but not the end of the world.

**Comment by sscheidt77** [comment]
When attempted to run the raspistill.gps, I get:

libgps.so.21: cannot open shared object file: No such file or directory

I have gpsd running and working.

**Comment by JamesH65** [comment]
looks like we are up to libgps28 now.

libgps_loader.h needs changing to reflect the move from 22 to 28....

**Comment by sscheidt77** [comment]
My apologies if I'm in the wrong place to be asking for how-to. 
I verified that I have libgps28 installed.
If I use the binary in the thread above: libgps.so.21: cannot open shared object file: No such file or directory
If I use raspistill -gps (up to date raspbian lite installation on a raspberry pi zero w) I get:
libgps.so.23: cannot open shared object file: No such file or directory

Suggestion on how to proceed with raspistill?

**Pull request merged**
