### PR TITLE
Add a flag to raspistill to start the frame number on something other th...

### PR DESCRIPTION
**Pull request by hwright**
...an 0 when taking multiple images.  This allows restarting raspistill without overwriting existing images.

### CODE REVIEW

**Comment by popcornmix** [comment]
@JamesH65 @6by9 any objections?

**Comment by 6by9** [comment]
No objections, although the renumbering is a little excessive.

**Comment by popcornmix** [comment]
@hwright can you fix the renumbering and force push?

**Comment by JamesH65** [comment]
This will also need to be rebased due to other changes in the same area.

**Comment by JamesH65** [comment]
Any further interest in this?

**Comment by 6by9** [comment]
I've cherry-picked the change, made mods, and pushed back to https://github.com/6by9/userland/tree/PR20160114
Assuming someone wants this, I'll create a new PR for it (I can't see a way to update this one as it isn't from my branch)

**Comment by popcornmix** [comment]
Superseded by https://github.com/raspberrypi/userland/pull/282

**Comment by hwright** [comment]
Thanks, and sorry I've been completely unresponsive on this.

(Life and all that.)

**Pull request closed without merging**
