### PR TITLE
Add range validation to ISO

### PR DESCRIPTION
**Pull request by emilbayes**
I don't know that this range is set in stone, but this is the range that @6by9 mentions is valid in this issue: https://github.com/raspberrypi/userland/issues/400

Also given that issue, should those specific values be strictly validated or is any int in-between valid?

### CODE REVIEW

**Comment by emilbayes** [comment]
Although, we have successfully used ISO values of `50`, but anything less seems to give exactly the same image (highly controlled environment)

**Comment by 6by9** [comment]
It's complicated.
ISO is meant to be a calibrated value. On OV5647 (V1.3 camera) ISO 100 = analogue gain of x1.0. On IMX219 (V2.1 camera) ISO 100 = analogue gain of x1.84, and therefore an ISO value lower than 100 can be achieved.
It's further complicated in that during preview/video modes there needs to be some flexibility to allow correct reproduction of a scene whilst also allowing things such as flicker avoidance to set the exposure time to a multiple of the mains flicker period. That requires some level of adjustment of the gain to compensate for fixed steps on the exposure time. To achieve that the tuning has fixed values for nominated ISO values of 100, 200, 400, and 800.
For stills mode, there is no such restriction, and therefore any value of ISO will be accepted and should be actioned.

TBH If you want fixed gains, then you're better off using the -ag and -dg commands to explicitly set analogue and digital gains.

**Comment by JamesH65** [comment]
Given @6by9 comments, I think this PR can be closed?

**Comment by 6by9** [comment]
Yes, will close. The range checking is going to give potentially odd results, and the comment only goes along with that.

**Pull request closed without merging**
