### PR TITLE
Raspicam update for manual analog & digital gains, and fix MMAL example

### PR DESCRIPTION
**Pull request by 6by9**
NB The Raspicam update requires mmal_parameter_camera.h to be merged from the latest firmware update for the enums of ```MMAL_PARAMETER_ANALOG_GAIN``` and ```MMAL_PARAMETER_DIGITAL_GAIN```.

### CODE REVIEW

**Comment by popcornmix** [comment]
Firmware and userland repos have been updated so this should be okay.

**Comment by popcornmix** [comment]
I think example_basic_2 has a missing include:
```
/home/dc4/projects/vc4/interface/mmal/test/examples/example_basic_2.c: In function 'main':
/home/dc4/projects/vc4/interface/mmal/test/examples/example_basic_2.c:271:19: error: implicit declaration of function 'log_format' [-Werror=implicit-function-declaration]
                   log_format(decoder->output[0]->format, decoder->output[0]);
                   ^
```

**Comment by 6by9** [comment]
Sorry, I'd stripped out log_format (a local function) to reduce the number of diffs, but couldn't rebuild due to the missing enums. I obviously missed this call :-(
I'll correct and repush.

**Comment by 6by9** [comment]
Corrected and verified working.

**Pull request merged**
